### ISSUE TITLE
dajGlos klasy Ryba

### ISSUE THREAD

**Issue by mkarbowiak** [december0123/obrona#3]
Nie jestem do końca przekonany, czy jest to dobry przykład. Czy nie dowiedziono naukowo, iż ryby nie mają głosu? Wydaje mi się, że metoda _dajGlos_ wywołana na obiekcie typu _Ryba_ powinna co najmniej zgłosić jakiś wyjątek, jeśli nie error informujący, iż taka operacja nie może zostać wykonana na klasie _Ryba_.

**Comment by kmachnicki** [comment]
Myślę, że jest to kwestia czystej spójności językowej nazewnictwa czynności wykonywanej przez obiekty będące pochodnymi klasy Zwierzę. Chodzi tutaj o sprawę komunikacji między osobnikami danego gatunku, nie zaś o zrozumienie intergatunkowe, czyli nic innego jak wydanie brzmienia z narządów danego gatunku do tego przystosowanych. A ryby, co zostało dowiedzione przez amerykańskich naukowców posługujących się harmonizerami kwantowymi punktu osobliwego rozszczepienia, posiadają zdolność wydawania dźwięków poprzez zmianę napięcia ściany pęcherza pławnego. Częstotliwość tychże dźwięków jest jednakże zbyt niska, aby były słyszalne przez istoty humanoidalne.

**Comment by mkarbowiak** [comment]
Pragnę zaznaczyć, iż wspomniany pęcherz pławny nie występuje u wszystkich ryb. Należy zatem zastanowić się, czy klasa _Ryba_ powinna przeciążać metodę _dajGlos_, czy raczej powinno się stworzyć klasy pochodne ryb, które faktycznie dźwięk wydawać mogą. Odsyłam do sprawdzonego źródła: https://pl.wikipedia.org/wiki/P%C4%99cherz_p%C5%82awny

**Comment by kmachnicki** [comment]
To, iż jeno część gatunków ryb posiada ową zdolność (szczególnie z gromady _akwarystów_, a także gatunki napływowe _imigrantus nigerus_ oraz niechybnie _falluso rektus_), jako żywo, faktem niezaprzeczalnym jest. Gatunków takich jednakowoż niezliczone ilości egzystuje, a fakt wymieniania owych wszystkich gatunków wyłącznie dla ukazania cech polimorficznych paradygmatów programowania obiektowego, mija się z celem. Ukazana została zatem w przykładzie ta funkcja _dajGlos_ w formie abstrakcyjnej, co zgodne jest z przedstawioną w podrozdziale 1.2 definicją abstrakcyjności. cyt.: _[...] poziom ogólności, pozwala nam na upraszczanie problemu poprzez zredukowanie właściwości do jedynie tych kluczowych_.

**Comment by mkarbowiak** [comment]
Dziękuję za wyjaśnienie, zamykam.

**Comment by december0123** [comment]
Mam nadzieję, że Szanowna Komisja specjalności INT doceni Waszą wiedzę dotyczącą ryb :D
